name: Deploy
on:
  push:
    branches:
      - master
      - staging

concurrency: deploy-${{ github.ref }}

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
      - name: Lint lock file
        run: npx lockfile-lint --type npm --path package-lock.json -o "https:" -o "file:" --allowed-hosts npm
      # no tests yet
      # - name: Test
      #   run: cd "npm test

  # build_deploy_application:
  #   needs: [lint-test]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: actions/setup-node@v3
  #       with:
  #         node-version-file: .nvmrc
  #     - name: Configure AWS credentials
  #       uses: aws-actions/configure-aws-credentials@v2
  #       with:
  #         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #         aws-region: '${{ vars.AWS_DEFAULT_REGION }}'
  #     - name: Install dependencies
  #       run: cd "npm ci
  #     - name: Deploy
  #       run: npx lockfile-lint --type npm --path package-lock.json -o "https:" -o "file:" --allowed-hosts npm
